#!/bin/bash
set -e

SOURCE_DIR="$(cd "$(dirname "$0")/skills" && pwd)"
CLAUDE_SKILL_DIR="$HOME/.claude/skills"
CODEX_SKILL_DIR="${CODEX_HOME:-$HOME/.codex}/skills"
CODEX_PROMPT_DIR="${CODEX_HOME:-$HOME/.codex}/prompts"
GAUNTLETTE_PROMPT_MARKER="Generated by gauntlette install.sh"

# TODO: these should be named the proper thing on disk. having this indirection makes no sense.
SKILL_LINKS=(
  "gauntlette-help:gauntlette-help"
  "gauntlette-start:survey-and-plan"
  "gauntlette-ceo-review:gauntlette-ceo-review"
  "gauntlette-product-review:gauntlette-ceo-review"
  "gauntlette-design-review:gauntlette-design-review"
  "gauntlette-ux-review:gauntlette-design-review"
  "gauntlette-eng-review:gauntlette-eng-review"
  "gauntlette-arch-review:gauntlette-eng-review"
  "gauntlette-fresh-eyes:fresh-eyes"
  "gauntlette-cso-review:cso-review"
  "gauntlette-implement:implement"
  "gauntlette-code-review:code-review"
  "gauntlette-quality-check:quality-check"
  "gauntlette-human-review:human-review"
  "gauntlette-ship-it:ship-it"
)

CODEX_PROMPT_WRAPPERS=(
  "gauntlette-help|gauntlette-help|Show preferred gauntlette commands, pipeline order, and current plan status."
  "gauntlette-start|survey-and-plan|Create the design doc and active plan, orient on codebase, and run the planning interview."
  "gauntlette-ceo-review|gauntlette-ceo-review|Challenge the idea itself: scope, value, and risk."
  "gauntlette-design-review|gauntlette-design-review|Run visual design review with wireframes, state diagrams, and design ratings."
  "gauntlette-eng-review|gauntlette-eng-review|Run engineering review with architecture diagrams, failure modes, and test plan."
  "gauntlette-fresh-eyes|fresh-eyes|Run an independent adversarial review from fresh context."
  "gauntlette-cso-review|cso-review|Run an optional security audit for secrets, supply chain, auth, injection, infra, and privacy."
  "gauntlette-implement|implement|Build the feature from the active Gauntlette plan."
  "gauntlette-code-review|code-review|Run a post-implementation adversarial code review."
  "gauntlette-quality-check|quality-check|Run E2E browser QA with diff-aware automation."
  "gauntlette-human-review|human-review|Run the human review checklist before shipping."
  "gauntlette-ship-it|ship-it|Run the ship workflow: tests, version, changelog, merge, deploy, and push."
)

# Check source exists
if [ ! -d "$SOURCE_DIR" ]; then
  echo "ERROR: skills/ not found. Run from the gauntlette repo root."
  exit 1
fi

# Generate SKILL.md files from templates
REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$REPO_ROOT/gen-skills.sh" ]; then
  echo "Generating skills from templates..."
  bash "$REPO_ROOT/gen-skills.sh"
  echo ""
fi

link_skill_root() {
  local skill_dir="$1"
  local gauntlette_dir="$skill_dir/gauntlette"

  mkdir -p "$skill_dir"

  if [ -L "$gauntlette_dir" ]; then
    echo "Updating existing symlink: $gauntlette_dir"
    rm "$gauntlette_dir"
  elif [ -d "$gauntlette_dir" ]; then
    echo "ERROR: $gauntlette_dir exists and is not a symlink. Remove it first."
    exit 1
  fi

  ln -s "$SOURCE_DIR" "$gauntlette_dir"
  echo "Linked: $gauntlette_dir -> $SOURCE_DIR"
}

link_skill() {
  local skill_dir="$1"
  local target_name="$2"
  local source_name="$3"
  local target="$skill_dir/$target_name"

  if [ -L "$target" ]; then
    local existing
    existing=$(readlink "$target")
    if [[ "$existing" != gauntlette/* ]]; then
      echo "SKIP: $target_name -> $existing (owned by another project, not overwriting)"
      return
    fi
    rm "$target"
  elif [ -d "$target" ]; then
    echo "SKIP: $target_name is a directory (owned by another project, not overwriting)"
    return
  fi

  ln -s "gauntlette/$source_name" "$target"
  echo "Linked: /$target_name"
}

yaml_quote() {
  local value
  value=$(printf "%s" "$1" | sed "s/'/''/g")
  printf "'%s'" "$value"
}

write_codex_prompt_wrapper() {
  local prompt_name="$1"
  local skill_name="$2"
  local description="$3"
  local target="$CODEX_PROMPT_DIR/$prompt_name.md"
  local temp="$target.tmp.$$"

  mkdir -p "$CODEX_PROMPT_DIR"

  if [ -e "$target" ] || [ -L "$target" ]; then
    if [ -L "$target" ]; then
      echo "SKIP: /prompts:$prompt_name is a symlink (not overwriting)"
      return
    fi

    if ! grep -Fq "$GAUNTLETTE_PROMPT_MARKER" "$target" 2>/dev/null; then
      echo "SKIP: /prompts:$prompt_name exists and is not owned by gauntlette"
      return
    fi
  fi

  {
    printf -- "---\n"
    printf "description: "
    yaml_quote "$description"
    printf "\n"
    printf "argument-hint: [ARGUMENTS]\n"
    printf -- "---\n\n"
    printf "<!-- %s. Do not edit directly. -->\n\n" "$GAUNTLETTE_PROMPT_MARKER"
    printf "Use the \`%s\` skill now. Treat this as the Codex compatibility wrapper for \`/prompts:%s\`.\n\n" "$skill_name" "$prompt_name"
    printf "If arguments were supplied, preserve them as request context: \$ARGUMENTS.\n\n"
    printf "Follow the skill's instructions exactly.\n"
  } > "$temp"

  mv "$temp" "$target"
  echo "Wrote: /prompts:$prompt_name"
}

for SKILL_DIR in "$CLAUDE_SKILL_DIR" "$CODEX_SKILL_DIR"; do
  link_skill_root "$SKILL_DIR"

  for LINK in "${SKILL_LINKS[@]}"; do
    TARGET_NAME="${LINK%%:*}"
    SOURCE_NAME="${LINK##*:}"
    link_skill "$SKILL_DIR" "$TARGET_NAME" "$SOURCE_NAME"
  done

  echo ""
done

for WRAPPER in "${CODEX_PROMPT_WRAPPERS[@]}"; do
  IFS='|' read -r PROMPT_NAME SKILL_NAME DESCRIPTION <<< "$WRAPPER"
  write_codex_prompt_wrapper "$PROMPT_NAME" "$SKILL_NAME" "$DESCRIPTION"
done

echo ""
echo "Installed gauntlette into:"
echo "  - $CLAUDE_SKILL_DIR"
echo "  - $CODEX_SKILL_DIR"
echo "  - $CODEX_PROMPT_DIR (Codex custom prompt wrappers)"
echo "Conflicts (if any) listed above as SKIP."
echo "Restart Claude Code or Codex, or open a new Codex chat, to pick up new skills and prompts."
