#!/bin/bash
set -e

CLAUDE_SKILL_DIR="$HOME/.claude/skills"
CODEX_SKILL_DIR="${CODEX_HOME:-$HOME/.codex}/skills"
CODEX_PROMPT_DIR="${CODEX_HOME:-$HOME/.codex}/prompts"
GAUNTLETTE_PROMPT_MARKER="Generated by gauntlette install.sh"

CODEX_PROMPT_NAMES=(
  "gauntlette-help"
  "gauntlette-start"
  "gauntlette-ceo-review"
  "gauntlette-design-review"
  "gauntlette-eng-review"
  "gauntlette-fresh-eyes"
  "gauntlette-cso-review"
  "gauntlette-implement"
  "gauntlette-code-review"
  "gauntlette-quality-check"
  "gauntlette-human-review"
  "gauntlette-ship-it"
)

for SKILL_DIR in "$CLAUDE_SKILL_DIR" "$CODEX_SKILL_DIR"; do
  GAUNTLETTE_DIR="$SKILL_DIR/gauntlette"

  for TARGET in "$SKILL_DIR"/*; do
    if [ ! -L "$TARGET" ]; then
      continue
    fi

    SKILL=$(basename "$TARGET")
    if [ "$SKILL" = "gauntlette" ]; then
      continue
    fi

    EXISTING=$(readlink "$TARGET")
    if [[ "$EXISTING" == gauntlette/* ]]; then
      rm "$TARGET"
      echo "Removed: /$SKILL from $SKILL_DIR"
    fi
  done

  if [ -L "$GAUNTLETTE_DIR" ]; then
    rm "$GAUNTLETTE_DIR"
    echo "Removed: $GAUNTLETTE_DIR"
  elif [ -d "$GAUNTLETTE_DIR" ]; then
    echo "SKIP: $GAUNTLETTE_DIR is a real directory, not a symlink. Remove manually."
  fi
done

for PROMPT_NAME in "${CODEX_PROMPT_NAMES[@]}"; do
  TARGET="$CODEX_PROMPT_DIR/$PROMPT_NAME.md"

  if [ ! -e "$TARGET" ] && [ ! -L "$TARGET" ]; then
    continue
  fi

  if [ -L "$TARGET" ]; then
    echo "SKIP: /prompts:$PROMPT_NAME is a symlink, not a gauntlette-generated prompt."
    continue
  fi

  if grep -Fq "$GAUNTLETTE_PROMPT_MARKER" "$TARGET" 2>/dev/null; then
    rm "$TARGET"
    echo "Removed: /prompts:$PROMPT_NAME from $CODEX_PROMPT_DIR"
  else
    echo "SKIP: /prompts:$PROMPT_NAME is not owned by gauntlette."
  fi
done

echo ""
echo "Gauntlette uninstalled. Restart Claude Code or Codex, or open a new Codex chat, to take effect."
