#!/bin/bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GAUNTLETTE_PROMPT_MARKER="Generated by gauntlette install.sh"

COMMANDS=(
  "gauntlette-help"
  "gauntlette-start"
  "gauntlette-ceo-review"
  "gauntlette-design-review"
  "gauntlette-eng-review"
  "gauntlette-fresh-eyes"
  "gauntlette-cso-review"
  "gauntlette-implement"
  "gauntlette-code-review"
  "gauntlette-quality-check"
  "gauntlette-human-review"
  "gauntlette-ship-it"
)

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

run_install() {
  local home_dir="$1"
  local codex_dir="$2"
  local output="$3"

  HOME="$home_dir" CODEX_HOME="$codex_dir" bash "$REPO_ROOT/install.sh" > "$output"
}

run_uninstall() {
  local home_dir="$1"
  local codex_dir="$2"
  local output="$3"

  HOME="$home_dir" CODEX_HOME="$codex_dir" bash "$REPO_ROOT/uninstall.sh" > "$output"
}

assert_generated_prompts() {
  local codex_dir="$1"
  local prompt_dir="$codex_dir/prompts"
  local count

  for command in "${COMMANDS[@]}"; do
    local file="$prompt_dir/$command.md"
    [ -f "$file" ] || fail "missing prompt wrapper: $file"
    grep -Fq "$GAUNTLETTE_PROMPT_MARKER" "$file" || fail "missing ownership marker in $file"
    grep -Fq '$ARGUMENTS' "$file" || fail "missing literal \$ARGUMENTS in $file"
    grep -Fq "/prompts:$command" "$file" || fail "missing /prompts:$command reference in $file"
  done

  count=$(find "$prompt_dir" -maxdepth 1 -type f -name 'gauntlette-*.md' | wc -l | tr -d ' ')
  [ "$count" = "${#COMMANDS[@]}" ] || fail "expected ${#COMMANDS[@]} prompt wrappers, found $count"
}

assert_prompts_removed() {
  local codex_dir="$1"
  local prompt_dir="$codex_dir/prompts"

  for command in "${COMMANDS[@]}"; do
    [ ! -e "$prompt_dir/$command.md" ] || fail "prompt wrapper was not removed: $prompt_dir/$command.md"
  done
}

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

home_clean="$tmp/home-clean"
codex_clean="$tmp/codex-clean"

run_install "$home_clean" "$codex_clean" "$tmp/install-clean.out"
assert_generated_prompts "$codex_clean"

run_install "$home_clean" "$codex_clean" "$tmp/install-clean-repeat.out"
assert_generated_prompts "$codex_clean"

run_uninstall "$home_clean" "$codex_clean" "$tmp/uninstall-clean.out"
assert_prompts_removed "$codex_clean"

home_conflict="$tmp/home-conflict"
codex_conflict="$tmp/codex-conflict"
mkdir -p "$codex_conflict/prompts"
printf "user-owned prompt\n" > "$codex_conflict/prompts/gauntlette-help.md"

run_install "$home_conflict" "$codex_conflict" "$tmp/install-conflict.out"
grep -Fxq "user-owned prompt" "$codex_conflict/prompts/gauntlette-help.md" || fail "user-owned prompt was overwritten"
grep -Fq "SKIP: /prompts:gauntlette-help exists and is not owned by gauntlette" "$tmp/install-conflict.out" || fail "missing conflict skip message"
[ -f "$codex_conflict/prompts/gauntlette-start.md" ] || fail "non-conflicting prompt was not generated"

run_uninstall "$home_conflict" "$codex_conflict" "$tmp/uninstall-conflict.out"
grep -Fxq "user-owned prompt" "$codex_conflict/prompts/gauntlette-help.md" || fail "user-owned prompt was removed"
[ ! -e "$codex_conflict/prompts/gauntlette-start.md" ] || fail "owned prompt was not removed during conflict uninstall"

echo "install/uninstall smoke test passed"
